apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: book-review-eks
  region: eu-north-1
nodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
