apiVersion: v1
kind: Secret
metadata:
  name: book-review-secret
  namespace: book-review
type: Opaque
stringData:
  DB_PASS: "my-secret-pw"
  JWT_SECRET: "mysecretkey"
  MYSQL_ROOT_PASSWORD: "my-secret-pw"